server:
  port: 8080
  address: 0.0.0.0

spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    status-page-url: http://localhost:8080/student/actuator/health
    health-check-url: http://localhost:8080/student/actuator/health
    home-page-url: http://localhost:8080/student/
    non-secure-port: 8080
    non-secure-port-enabled: true
    prefer-ip-address: true