#dbc:mysql://localhost:3306/fb
jdbc.url=Nw3xa3mU0eJSLyE8T7xD5tVVKE1sqVXKBc15xCKnKIk=
envirnment=LOCAL
#localhost
hostname=VKdYnq1Fxq4E4KIKeTgZOQ==
jdbc.schemaName=O4ym+mbdF1GjjvFQ3z9/qQ==
jdbc.username=A8Tkk+Mk7y3at4wFgWvMTw==
jdbc.password=oDdtKl/DovKYyVDH2Xc/Xw==