spring.profiles.active=dev

defaultPass = Z2RA+AuxGZ87L8E6FFQvqQ==
supperUser = indrajeet
superUserEmail = indrajeet.sawarkar@gmail.com
defaultLocal = en
#also change the log4j.xml with above email.

#DataBase connection properties
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
hibernate.show_sql=false

expiryString=3KJTp2FIe0oqedAc4lRTnLeoCZuSNn1+eupEAdnj+cb8Q05eVW/zO7Dr3SUbTnpl
#Time in UTC.It is for 12 AM.
cronExpression=0 30 18 * * ?
dataLoaderExpression=0 30 18 * * ?
enableEffortSystem=nG/NkQjAgmaix9R2fLUrPA==
enableReferralReward=YES
enableStudentFeeReminder=YES
sendBirthdayEmail=YES
key=XMzDdG4D03CKm2IxIWQw7g==
version=1.1
gp=tsECmOeDdhYo18MwiTOqpDXpd+gEcVSaLxHSA/xVpng=
dbBackupEnable=YES
dbBackups3bucketName=356723301672-dbbackup-fb

spring.application.name=student
spring.main.allow-bean-definition-overriding=true
management.security.enabled=false
