#jdbc:mysql://fresher-buddy-new.c8pwq24yavum.us-east-1.rds.amazonaws.com:3306/fb
jdbc.url=2yoPe/0S3eRO4aTR/x5D6pdfnu0ja5JrzXwA3HE0SDbGx+yRcG+CQmI+n0ul8qaMlH+LO3wTX3WZsVFzGu0mPb5yQy1JIbyZVv4FYdoiGyk=
envirnment=SERVER
#REmyMqT0UYfR2myoXQs5gDznKxGn5a7ggBNM080xbC2QntrZQFGUen6zasgHnQctdRDboNr1U4WJ8oa2RgwGdg==
hostname=REmyMqT0UYfR2myoXQs5gDznKxGn5a7ggBNM080xbC2QntrZQFGUen6zasgHnQctdRDboNr1U4WJ8oa2RgwGdg====
jdbc.schemaName=O4ym+mbdF1GjjvFQ3z9/qQ==
jdbc.username=A8Tkk+Mk7y3at4wFgWvMTw==
jdbc.password=oDdtKl/DovKYyVDH2Xc/Xw==

eureka.client.healthcheck.enabled=true
eureka.client.service-url.defaultZone=http://54.82.100.135:8761/eureka/

eureka.instance.status-page-url=https://student.fresherbuddy.in/student/actuator/health
eureka.instance.health-check-url=https://student.fresherbuddy.in/student/actuator/health
eureka.instance.home-page-url=https://student.fresherbuddy.in/student/
eureka.instance.ip-address=${server.address}
eureka.instance.non-secure-port=8080
eureka.instance.non-secure-port-enabled=true
eureka.instance.prefer-ip-address=true
