
# ============================================
# Application Configuration
# ============================================

$appname = "fb"
$accId = 356723301672
$RepositoryName = $appname
$Region = "us-east-1"

# Source Maven project
$MavenProjectPath = "D:\latestworks\tpo\$appname"

# Docker build directory
$DockerBuildPath = "D:\latestworks\tpo\fb\ekctl-EKS-docker\kubectl\dockerImageCreation\$appname"

# WAR file generated by Maven
$WarSource = "$MavenProjectPath\target\FB.war"

# WAR file required by Dockerfile
$WarDestination = "$DockerBuildPath\FB.war"

# Docker configuration
$ImageName = "$appname-tomcat"
$ContainerName = "$appname-container"
$HostPort = 8080
$ContainerPort = 8080


# ============================================
# Step 1 - Maven Build
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 1 - Maven Build" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Set-Location $MavenProjectPath

Write-Host "Maven project: $MavenProjectPath" -ForegroundColor Yellow
Write-Host "Running: mvn install" -ForegroundColor Yellow

mvn install

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Maven build failed." -ForegroundColor Red
    exit 1
}

Write-Host "Maven build completed successfully." -ForegroundColor Green


# ============================================
# Step 2 - Check WAR
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 2 - Check WAR File" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

if (-not (Test-Path $WarSource)) {
    Write-Host "ERROR: WAR file was not generated." -ForegroundColor Red
    Write-Host "Expected: $WarSource" -ForegroundColor Red
    exit 1
}

Write-Host "WAR found:" -ForegroundColor Green
Write-Host $WarSource


# ============================================
# Step 3 - Go to Docker Build Directory
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 3 - Docker Build Directory" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Set-Location $DockerBuildPath

Write-Host "Docker build directory:" -ForegroundColor Yellow
Write-Host $DockerBuildPath


# ============================================
# Step 4 - Copy WAR
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 4 - Copy WAR File" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Copy-Item `
    -Path $WarSource `
    -Destination $WarDestination `
    -Force

if (-not (Test-Path $WarDestination)) {
    Write-Host "ERROR: Failed to copy FB.war." -ForegroundColor Red
    exit 1
}

Write-Host "WAR copied successfully:" -ForegroundColor Green
Write-Host "$WarSource"
Write-Host "       ->"
Write-Host "$WarDestination"


# ============================================
# Step 5 - Docker Check
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 5 - Check Docker" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

docker --version

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker is not available." -ForegroundColor Red
    exit 1
}

Write-Host "Docker is available." -ForegroundColor Green


# ============================================
# Step 6 - Build Docker Image
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 6 - Build Docker Image" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Write-Host "Image Name: $ImageName" -ForegroundColor Yellow

docker build -t $ImageName .

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker image build failed." -ForegroundColor Red
    exit 1
}

Write-Host "Docker image created successfully." -ForegroundColor Green


# ============================================
# Step 7 - Remove Existing Container
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 7 - Remove Existing Container" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

$ExistingContainer = docker ps -a `
    --filter "name=^${ContainerName}$" `
    --format "{{.Names}}"

if ($ExistingContainer -eq $ContainerName) {

    Write-Host "Removing existing container: $ContainerName" -ForegroundColor Yellow

    docker rm -f $ContainerName

    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Failed to remove existing container." -ForegroundColor Red
        exit 1
    }
}


# ============================================
# Step 8 - Run Container
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 8 - Run Docker Container" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

docker run -d `
    --name $ContainerName `
    -p "${HostPort}:${ContainerPort}" `
    $ImageName

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker container failed to start." -ForegroundColor Red
    exit 1
}

Write-Host "Container started successfully." -ForegroundColor Green


# ============================================
# Step 9 - Display Status
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Application Started Successfully" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Write-Host ""
Write-Host "Application : $appname" -ForegroundColor White
Write-Host "Image       : $ImageName" -ForegroundColor White
Write-Host "Container   : $ContainerName" -ForegroundColor White
Write-Host "Region      : $Region" -ForegroundColor White
Write-Host ""

Write-Host "URL:" -ForegroundColor Green
Write-Host "http://localhost:$HostPort" -ForegroundColor Cyan

Write-Host ""
Write-Host "FB Application:" -ForegroundColor Green
Write-Host "http://localhost:$HostPort/FB/" -ForegroundColor Cyan

Write-Host ""
Write-Host "Container Status:" -ForegroundColor Yellow
docker ps --filter "name=$ContainerName"

Write-Host ""
Write-Host "Logs:" -ForegroundColor Yellow
Write-Host "docker logs -f $ContainerName" -ForegroundColor White

Write-Host ""
Write-Host "Stop container:" -ForegroundColor Yellow
Write-Host "docker stop $ContainerName" -ForegroundColor White

