bucketName = fresherbuddy-files-server
bucketName = fresherbuddy-files-local
S3Key=t/VIZluq6P3UjsKCrmercu62sDWCVosyoNmq+Y6FuXw=
S3Key1=qINXerahYkiNX25puuy/McWVylvyf+xRW7d+kDQrjTMtvmpEY6Zvcd7X5q8nuk2r
region=ap-south-1
key=XMzDdG4D03CKm2IxIWQw7g==