version: 0.2

env:
  shell: cmd
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - installjar.bat
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/FB.war