mobileTestingFlag=false
#This is for virtual device not for mobile.
localhost = 10.0.2.2:8888
#This is for mobile device.Change it to URL on production.Note: Please replace with latest IP.
device_localhost = https://student.fresherbuddy.in
#device_localhost = http://192.168.41.113:8080
