#jdbc:mysql://host.docker.internal:3306/fb if running application using Docker
jdbc.url=tqMxecikBt+hEi1WArP3fKrkQXrFElwOo5rk/rgCzdjZzzpe9rVqV22QT1DQbMqa
envirnment=LOCAL
#host.docker.internal
hostname=UrAP2gCvtNCrKCtYmMcBDIsEdfAsYtUFS5BH/ZUrGeA===
jdbc.schemaName=O4ym+mbdF1GjjvFQ3z9/qQ==
jdbc.username=A8Tkk+Mk7y3at4wFgWvMTw==
jdbc.password=oDdtKl/DovKYyVDH2Xc/Xw==

eureka.client.healthcheck.enabled=true
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/

eureka.instance.status-page-url=http://host.docker.internal:8082/exam/actuator/health
eureka.instance.health-check-url=http://host.docker.internal:8082/exam/actuator/health
eureka.instance.home-page-url=http://host.docker.internal:8082/exam/
eureka.instance.ip-address=${server.address}
eureka.instance.non-secure-port=8080
eureka.instance.non-secure-port-enabled=true
eureka.instance.prefer-ip-address=true