defaultPass = Z2RA+AuxGZ87L8E6FFQvqQ==
supperUser = indrajeet
superUserEmail = indrajeet.sawarkar@gmail.com
defaultLocal = en
#also change the log4j.xml with above email.

#DataBase connection properties
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
#jdbc:mysql://fresher-buddy-new.cu508syy6jlv.us-east-1.rds.amazonaws.com/fb
jdbc.url=2yoPe/0S3eRO4aTR/x5D6pdfnu0ja5JrzXwA3HE0SDZRto6adafkazR1HJYXgfaglH+LO3wTX3WZsVFzGu0mPQ2pXJPuw8Elb6kTFCXU8Qw=
envirnment=SERVER

#jdbc:mysql://localhost:3306/fb
#jdbc.url=Nw3xa3mU0eJSLyE8T7xD5tVVKE1sqVXKBc15xCKnKIk=
# use jdbc:mysql://host.docker.internal:3306/fb if running application using Docker
jdbc.url=tqMxecikBt+hEi1WArP3fKrkQXrFElwOo5rk/rgCzdjZzzpe9rVqV22QT1DQbMqa
envirnment=LOCAL
#localhost
hostname=VKdYnq1Fxq4E4KIKeTgZOQ==
jdbc.schemaName=O4ym+mbdF1GjjvFQ3z9/qQ==
jdbc.username=A8Tkk+Mk7y3at4wFgWvMTw==
jdbc.password=oDdtKl/DovKYyVDH2Xc/Xw==
expiryString=3KJTp2FIe0oqedAc4lRTnLeoCZuSNn1+eupEAdnj+cb8Q05eVW/zO7Dr3SUbTnpl
hibernate.show_sql=false
#Time in UTC.It is for 12 AM.
cronExpression=0 30 18 * * ?
dataLoaderExpression=0 30 18 * * ?
enableEffortSystem=nG/NkQjAgmaix9R2fLUrPA==
enableReferralReward=YES
enableStudentFeeReminder=YES
sendBirthdayEmail=YES
key=XMzDdG4D03CKm2IxIWQw7g==
version=1.1
gp=fQ+ZtxTGIPzKy1oJXCZANt2w6ETRKMb28Cl8/RhXBFg=
dbBackupEnable=YES


#jdbc:mysql://localhost:3306/indwaar_tpo
#jdbc.url=Nw3xa3mU0eJSLyE8T7xD5imuAL/wI/HmHu9XzAxvpKm+TaLwrlrgFgmnkzMzHH3T
#indwaar_tpo
#jdbc.schemaName=h3s+bEPZiGZl4cP+IYrwpQ==
#root
#jdbc.username=A8Tkk+Mk7y3at4wFgWvMTw==
#ulta
#jdbc.password=oDdtKl/DovKYyVDH2Xc/Xw==


#indrajeet
#jdbc.username=6uTf5MvUs+1iCYMm9DeykA==
#JeeT@1984
#jdbc.password=0wWTLHghtseixSrrvuTVDw==


