bucketName = 356723301672-fresherbuddy-files-server
#bucketName = fresherbuddy-files-local
S3Key=s2NosuQwHOqjo9jx6LmS7Mj22AJIaxTddpGqgtCL2UQ=
S3Key1=ubhlw51keb8cmsviqB2rJgdhcfNjXW2q2WHeCoC8kCSKkxtK7f1ax/Ub66/pXfX1
region=us-east-1
key=XMzDdG4D03CKm2IxIWQw7g==