package tpo.hibernate;

import java.util.Date;

import tpo.util.TpoUtil;


/**
 * EmployeeEfforts generated by MyEclipse - Hibernate Tools
 */

public class EmployeeEfforts  implements java.io.Serializable {


    // Fields    

     private Long effortid;
     private Logindetails logindetails;
     private Date sdate;
     private Long project;
     private Long module;
     private String description;
     private Integer time;
     private String remarks;
     private Boolean leavestatus;
     private String leaveday;
     private String createdBy;
     private String status;


    // Constructors

    /** default constructor */
    public EmployeeEfforts() {
    }

    
    /** full constructor */
    public EmployeeEfforts(Logindetails logindetails, Date sdate, Long project, Long module, String description, Integer time, String remarks, Boolean leavestatus, String leaveday) {
        this.logindetails = logindetails;
        this.sdate = sdate;
        this.project = project;
        this.module = module;
        this.description = description;
        this.time = time;
        this.remarks = remarks;
        this.leavestatus = leavestatus;
        this.leaveday = leaveday;
    }

   
    // Property accessors

    public Long getEffortid() {
        return this.effortid;
    }
    
    public void setEffortid(Long effortid) {
        this.effortid = effortid;
    }

   

    public Logindetails getLogindetails() {
		return logindetails;
	}


	public void setLogindetails(Logindetails logindetails) {
		this.logindetails = logindetails;
	}


	public Date getSdate() {
        return this.sdate;
    }
    
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }

    public Long getProject() {
        return this.project;
    }
    
    public void setProject(Long project) {
        this.project = project;
    }

    public Long getModule() {
        return this.module;
    }
    
    public void setModule(Long module) {
        this.module = module;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getTime() {
        return this.time;
    }
    
    public void setTime(Integer time) {
        this.time = time;
    }

    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Boolean getLeavestatus() {
        return this.leavestatus;
    }
    
    public void setLeavestatus(Boolean leavestatus) {
        this.leavestatus = leavestatus;
    }

    public String getLeaveday() {
        return this.leaveday;
    }
    
    public void setLeaveday(String leaveday) {
        this.leaveday = leaveday;
    }


	public String getCreatedBy() {
		return createdBy;
	}


	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}
	
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer("Effort ID=");
		buffer.append(String.valueOf(effortid));
		buffer.append(",Date=");
		buffer.append(TpoUtil.getDateToStringInddmmyyyy(sdate));
		buffer.append(",Project=");
		buffer.append(String.valueOf(project));
		buffer.append(",Module=");
		buffer.append(String.valueOf(module));
		return buffer.toString();
	}
	
	

}