package tpo.hibernate;



/**
 * Module generated by MyEclipse - Hibernate Tools
 */

public class Module  implements java.io.Serializable {


    // Fields    

     private Long moduleid;
     private Project project;
     private String modulename;
     private Integer status;
     private String createdBy;


    // Constructors

    /** default constructor */
    public Module() {
    }

    
    /** full constructor */
    public Module(Project project, String modulename, Integer status) {
        this.project = project;
        this.modulename = modulename;
        this.status = status;
    }

   
    // Property accessors

    public Long getModuleid() {
        return this.moduleid;
    }
    
    public void setModuleid(Long moduleid) {
        this.moduleid = moduleid;
    }

    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    public String getModulename() {
        return this.modulename;
    }
    
    public void setModulename(String modulename) {
        this.modulename = modulename;
    }

    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }


	public String getCreatedBy() {
		return createdBy;
	}


	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
   
}