package tpo.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Project generated by MyEclipse - Hibernate Tools
 */

public class Project  implements java.io.Serializable {


    // Fields    

     private Long projectid;
     private String projectname;
     private Integer status;
     private String createdBy;
     private Set modules = new HashSet(0);


    // Constructors

    /** default constructor */
    public Project() {
    }

    
    /** full constructor */
    public Project(String projectname, Integer status, Set modules) {
        this.projectname = projectname;
        this.status = status;
        this.modules = modules;
    }

   
    // Property accessors

    public Long getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(Long projectid) {
        this.projectid = projectid;
    }

    public String getProjectname() {
        return this.projectname;
    }
    
    public void setProjectname(String projectname) {
        this.projectname = projectname;
    }

    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Set getModules() {
        return this.modules;
    }
    
    public void setModules(Set modules) {
        this.modules = modules;
    }


	public String getCreatedBy() {
		return createdBy;
	}


	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}