# Database
# jdbc:mysql://localhost:3306/fb
jdbc.url=Nw3xa3mU0eJSLyE8T7xD5tVVKE1sqVXKBc15xCKnKIk=
jdbc.schemaName=O4ym+mbdF1GjjvFQ3z9/qQ==
jdbc.username=A8Tkk+Mk7y3at4wFgWvMTw==
jdbc.password=oDdtKl/DovKYyVDH2Xc/Xw==
envirnment=LOCAL
hostname=VKdYnq1Fxq4E4KIKeTgZOQ==

# Eureka
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=8080
eureka.instance.health-check-url=http://localhost:8080/FB/actuator/health
eureka.instance.status-page-url=http://localhost:8080/FB/actuator/health

