spring.profiles.active=dev

# Server
server.servlet.context-path=/FB
server.port=8080

# Spring
spring.application.name=fb
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.cloud.netflix.eureka=INFO
logging.level.org.hibernate=INFO

defaultPass = Z2RA+AuxGZ87L8E6FFQvqQ==
superUser = indrajeet
superUserEmail = indrajeet.sawarkar@gmail.com
defaultLocal = en
#also change the log4j.xml with above email.

#DataBase connection properties
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
hibernate.show_sql=false

expiryString=3KJTp2FIe0oqedAc4lRTnLeoCZuSNn1+eupEAdnj+cb8Q05eVW/zO7Dr3SUbTnpl
#Time in UTC.It is for 12 AM.
cronExpression=0 30 18 * * ?
dataLoaderExpression=0 30 18 * * ?
enableEffortSystem=nG/NkQjAgmaix9R2fLUrPA==
enableReferralReward=YES
enableStudentFeeReminder=YES
sendBirthdayEmail=YES
key=XMzDdG4D03CKm2IxIWQw7g==
version=1.1
gp=tsECmOeDdhYo18MwiTOqpDXpd+gEcVSaLxHSA/xVpng=
dbBackupEnable=YES
dbBackups3bucketName=356723301672-dbbackup-fb

backupPath=/home/ubuntu/indwaar/xml-config/tpo/backup/
dataLoader=/home/ubuntu/indwaar/xml-config/tpo/dataloader/