server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    non-secure-port: 8080
    health-check-url: http://localhost:8080/FB/actuator/health
    status-page-url: http://localhost:8080/FB/actuator/health

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.cloud.netflix.eureka: INFO
    org.hibernate: INFO