server:
  servlet:
    context-path: /FB

spring:
  application:
    name: fb

  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.cloud.netflix.eureka: INFO
    org.hibernate: INFO