#Set bleow property to YES if you want to enable SMS service
enableSMSApiForFB=YES
enableSMSApiForBB=NO

# msg91 Send SMS API
#Set bleow property to YES if you want to send sms through bulkSms
SmsThroughMsg91=NO
msg91MainUrl = https://control.msg91.com/api/sendhttp.php?
#Your authentication key
msg91param1Name = authkey
msg91param1Value = 192845AQgvZPhecs9h5a588552
#define route
msg91param2Name = route
msg91param2Value = FB
#Sender ID,While using route4 sender id should be 6 characters long.
msg91param3Name = sender
msg91param3Value = FBTEAM

#bulkSms Send SMS API
#Set bleow property to YES if you want to send sms through bulkSms
SmsThroughBulkSmsGateway=YES
bulkSmsMainUrl = http://login.bulksmsgateway.in/sendmessage.php?
bulkSmsParam1Name=user
bulkSmsParam1Value=indrajit92
bulkSmsParam2Name=password
bulkSmsParam2Value=j/hPuPO0OuW9Jdj05Ou22Q==
bulkSmsParam3Name=sender
bulkSmsParam3Value=FBTEAM
bulkSmsParam4Name=type
bulkSmsParam4Value=3

