
# ============================================
# Exam Application Configuration
# ============================================

$appname = "exam"
$accId = 542115677157
$RepositoryName = $appname
$Region = "us-east-1"

# Maven project directory
$MavenProjectPath = "D:\Mywork\$appname"

# Docker build directory
$DockerBuildPath = "D:\Mywork\fb\ekctl-EKS-docker\kubectl\dockerImageCreation\$appname"

# WAR generated by Maven
$WarSource = "$MavenProjectPath\target\exam.war"

# WAR required by Dockerfile
$WarDestination = "$DockerBuildPath\exam.war"

# Docker configuration
$ImageName = "$appname-tomcat"
$ContainerName = "$appname-container"

# Host port
$HostPort = 8082

# Container port
$ContainerPort = 8080


# ============================================
# Step 1 - Maven Build
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 1 - Maven Build" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Set-Location $MavenProjectPath

Write-Host "Maven Project:" -ForegroundColor Yellow
Write-Host $MavenProjectPath

Write-Host ""
Write-Host "Running: mvn install" -ForegroundColor Yellow

mvn install

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Maven build failed." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Maven build completed successfully." -ForegroundColor Green


# ============================================
# Step 2 - Check WAR File
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 2 - Check WAR File" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

if (-not (Test-Path $WarSource)) {
    Write-Host "ERROR: WAR file was not generated." -ForegroundColor Red
    Write-Host "Expected file:" -ForegroundColor Red
    Write-Host $WarSource -ForegroundColor Red
    exit 1
}

Write-Host "WAR file found:" -ForegroundColor Green
Write-Host $WarSource


# ============================================
# Step 3 - Docker Build Directory
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 3 - Docker Build Directory" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

if (-not (Test-Path $DockerBuildPath)) {
    Write-Host "ERROR: Docker build directory does not exist." -ForegroundColor Red
    Write-Host $DockerBuildPath -ForegroundColor Red
    exit 1
}

Set-Location $DockerBuildPath

Write-Host "Docker Build Directory:" -ForegroundColor Yellow
Write-Host $DockerBuildPath


# ============================================
# Step 4 - Copy WAR
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 4 - Copy WAR File" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Copy-Item `
    -Path $WarSource `
    -Destination $WarDestination `
    -Force

if (-not (Test-Path $WarDestination)) {
    Write-Host "ERROR: Failed to copy exam.war." -ForegroundColor Red
    exit 1
}

Write-Host "WAR copied successfully." -ForegroundColor Green

Write-Host ""
Write-Host "Source:" -ForegroundColor Yellow
Write-Host $WarSource

Write-Host ""
Write-Host "Destination:" -ForegroundColor Yellow
Write-Host $WarDestination


# ============================================
# Step 5 - Check Docker
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 5 - Check Docker" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

docker --version

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker is not installed or not running." -ForegroundColor Red
    exit 1
}

Write-Host "Docker is available." -ForegroundColor Green


# ============================================
# Step 6 - Build Docker Image
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 6 - Build Docker Image" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Write-Host "Building image:" -ForegroundColor Yellow
Write-Host $ImageName

docker build -t $ImageName .

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker image build failed." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Docker image built successfully." -ForegroundColor Green


# ============================================
# Step 7 - Remove Existing Container
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 7 - Remove Existing Container" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

$ExistingContainer = docker ps -a `
    --filter "name=^${ContainerName}$" `
    --format "{{.Names}}"

if ($ExistingContainer -eq $ContainerName) {

    Write-Host "Existing container found:" -ForegroundColor Yellow
    Write-Host $ContainerName

    Write-Host "Removing existing container..." -ForegroundColor Yellow

    docker rm -f $ContainerName

    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Failed to remove existing container." -ForegroundColor Red
        exit 1
    }

    Write-Host "Existing container removed." -ForegroundColor Green
}
else {
    Write-Host "No existing container found." -ForegroundColor Green
}


# ============================================
# Step 8 - Run Docker Container
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Step 8 - Start Docker Container" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Write-Host "Container:" -ForegroundColor Yellow
Write-Host $ContainerName

Write-Host ""
Write-Host "Port Mapping:" -ForegroundColor Yellow
Write-Host "${HostPort}:${ContainerPort}"

docker run -d `
    --name $ContainerName `
    -p "${HostPort}:${ContainerPort}" `
    $ImageName

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker container failed to start." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Docker container started successfully." -ForegroundColor Green


# ============================================
# Step 9 - Display Status
# ============================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Exam Application Started" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Write-Host ""
Write-Host "Application : $appname" -ForegroundColor White
Write-Host "Image       : $ImageName" -ForegroundColor White
Write-Host "Container   : $ContainerName" -ForegroundColor White
Write-Host "Region      : $Region" -ForegroundColor White
Write-Host "Account ID  : $accId" -ForegroundColor White

Write-Host ""
Write-Host "Tomcat URL:" -ForegroundColor Green
Write-Host "http://localhost:$HostPort" -ForegroundColor Cyan

Write-Host ""
Write-Host "Exam Application URL:" -ForegroundColor Green
Write-Host "http://localhost:$HostPort/exam/" -ForegroundColor Cyan

Write-Host ""
Write-Host "Container Status:" -ForegroundColor Yellow

docker ps --filter "name=$ContainerName"

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Useful Commands" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

Write-Host ""
Write-Host "View logs:" -ForegroundColor Yellow
Write-Host "docker logs -f $ContainerName"

Write-Host ""
Write-Host "Stop container:" -ForegroundColor Yellow
Write-Host "docker stop $ContainerName"

Write-Host ""
Write-Host "Start container:" -ForegroundColor Yellow
Write-Host "docker start $ContainerName"

Write-Host ""
Write-Host "Remove container:" -ForegroundColor Yellow
Write-Host "docker rm -f $ContainerName"

Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host " DONE" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
