apiVersion: v1
kind: Service
metadata:
  name: indrajeet-lb-app-service
spec:
  selector:
     app: indrajeet-app-deployment
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31999
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indrajeet-app-deployment
  labels:
    app: indrajeet-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: indrajeet-app-deployment
  template:
    metadata:
      labels:
        app: indrajeet-app-deployment
    spec:
      containers:
      - name: demo
        image: indrajeetsawarkar/bb:latest
        ports:
         - containerPort: 8080
      imagePullSecrets:
        - name: regcred
